### ISSUE TITLE
BUG: "Proxy target missing"

### ISSUE THREAD

**Issue by jakirkham** [binder-project/example-conda-environment#1]
Loads for a bit. Then message appears when clicking on the badge.

**Comment by ahmadia** [comment]
I believe this is just a random error that shows up, it's not related to the example itself.

**Comment by andrewosh** [comment]
Ah, yes this was an issue we had with the old proxy service we were using. We put in a fix that should prevent it, so I doubt anyone has seen this error in quite a while. I'll close this.
