### ISSUE TITLE
Update example for beta

### ISSUE THREAD

**Issue by jakirkham** [binder-project/example-conda-environment#4]
The current example doesn't seem to work with the beta version of Binder. Also tried a couple of forks, but didn't get anything to work either. Any thoughts on how to get example working with conda?

cc @yuvipanda @choldgraf

**Comment by choldgraf** [comment]
Could you open this at the new binderhub repo? https://github.com/jupyterhub/binderhub

Eventually we'll deprecate these repositories, but it is important to make sure examples don't break etc, so thanks for bringing this up!

**Comment by jakirkham** [comment]
This issue was moved to jupyterhub/binderhub#79
